"""empty message

Revision ID: 46d3cc10d346
Revises: 
Create Date: 2020-09-01 02:46:45.664984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d3cc10d346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameid',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('started', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('decks',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('card', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['gameid.code'], ),
    sa.PrimaryKeyConstraint('code', 'card')
    )
    op.create_table('hands',
    sa.Column('card', sa.String(length=2), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('player', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['gameid.code'], ),
    sa.PrimaryKeyConstraint('card', 'code', 'player')
    )
    op.create_table('players',
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['gameid.code'], ),
    sa.PrimaryKeyConstraint('name', 'code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('hands')
    op.drop_table('decks')
    op.drop_table('gameid')
    # ### end Alembic commands ###
