"""empty message

Revision ID: 90c355d05a8c
Revises: 941bbe9c4433
Create Date: 2020-09-02 21:39:27.322235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c355d05a8c'
down_revision = '941bbe9c4433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('deckType', sa.String(length=10), nullable=False))
    op.add_column('hands', sa.Column('cardType', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hands', 'cardType')
    op.drop_column('decks', 'deckType')
    # ### end Alembic commands ###
