"""empty message

Revision ID: 941bbe9c4433
Revises: 46d3cc10d346
Create Date: 2020-09-01 14:34:14.962789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941bbe9c4433'
down_revision = '46d3cc10d346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameid', sa.Column('lplayed', sa.Integer(), nullable=True))
    op.add_column('gameid', sa.Column('nlPlayed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gameid', 'nlPlayed')
    op.drop_column('gameid', 'lplayed')
    # ### end Alembic commands ###
